### ISSUE TITLE
Shadow vars in bessel_function.tcc

### ISSUE THREAD

**Issue by aj664** [emsr/tr29124_test#157]
hi, found your name in the header of a /mingw64/include/c++/7.2.0/tr1/besssel_function.tcc   this file contains lots of shadow vars.. who do i contact to fix them?    it's preventing being able to compile using -std=C++17

**Comment by emsr** [comment]
I am the person to contact.
If you have a patch please feel free to patch it.
Otherwise, send me the error messages and the invocation.
Actually, if you haven't already, the best thing to do is to open a bug report against libstdc++:
[gcc bugzilla](https://gcc.gnu.org/bugzilla/)
Add me to the cc: 3dw4rd

I will make sure that you changes make it here too.
Thanks you!

**Comment by emsr** [comment]
Sorry it took so long to answer, I was away from this project for a bit!  I'm glad you fond me. :-)

**Comment by emsr** [comment]
I'm actually not seeing this.
