### ISSUE TITLE
license

### ISSUE THREAD

**Issue by lkapelevich** [emsr/tr29124_test#177]
Heya. 
Is this code under any particular license? I can see a license in the history but not in the current main branch of the repo.

**Comment by emsr** [comment]
I've actually been struggling with that. I think I have to license it under LGPL3 since much of it has also been added to the gcc C++ standard library (libstdc++-v3). Also, some borrows heavily from GSL. The question is whether I can dual license it somehow.

I hope LGPL3 is ok.

This will inspire me to put a license file in there and set whatever flags in github.
